# Configuración de Netlify para un sitio de React
[build]
  command = "npm run build"
  publish = "dist"

# Configuración para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración específica para formularios
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

# Configuración de seguridad
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "form-action https:"

# Configuración de caché
[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 